# Generated by Django 4.0.5 on 2022-12-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_userprofile_email_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_email', models.EmailField(max_length=100)),
                ('c_subject', models.CharField(max_length=100)),
                ('c_message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(max_length=100, null=True, verbose_name='First name'),
        ),
    ]
