# Generated by Django 4.0.5 on 2022-12-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_contact_alter_userprofile_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='s_registe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('s_email', models.EmailField(max_length=100)),
                ('s_uname', models.CharField(max_length=100)),
                ('s_pwd1', models.CharField(max_length=50)),
                ('s_pwd2', models.CharField(max_length=50)),
            ],
        ),
        # migrations.CreateModel(
        #     name='u_registe',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('u_name', models.CharField(max_length=100)),
        #         ('u_email', models.EmailField(max_length=100)),
        #         ('u_uname', models.CharField(max_length=100)),
        #         ('u_pwd1', models.CharField(max_length=50)),
        #         ('u_pwd2', models.CharField(max_length=50)),
        #     ],
        # ),
        migrations.AlterField(
            model_name='contact',
            name='c_email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='c_message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='c_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='c_subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
    ]
